{% set version = "0.2.0" %}

package:
  name: pyinter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyinter/pyinter-{{ version }}.tar.gz
  sha256: c0c1717bef2b8c781776f97861133b27224d558169aa4bd2845d26868d7957bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pyinter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intiocean/pyinter
  summary: An interval package for Python.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danielnachun
